services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - VERSION=docker
    volumes:
      - ./plex/config:/config
      - ./plex/photos:/photos
      - ./plex/movies:/movies
      - ./plex/animated_movies:/animated_movies
      - ./plex/series:/series
    restart: always
    ports:
      - 32400:32400