apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: homelab
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./plex/config
        containerPath: /mnt/ssd/plex/config
      - hostPath: ./plex/data
        containerPath: /mnt/ssd/plex/data