apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plexserver
  name: plexserver
  namespace: plexserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plexserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plexserver
    spec:
      volumes:
        - name: nfs-plex-config
          persistentVolumeClaim:
            claimName: plexserver-pvc-config
        - name: nfs-data
          persistentVolumeClaim:
            claimName: plexserver-pvc-data
      containers:
        - name: plexserver
          envFrom:
            - configMapRef:
                name: plexserver-config-map
          image: linuxserver/plex:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 32400
              name: pms-web
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 3005
              name: plex-companion
              protocol: TCP
            - containerPort: 5353
              name: discovery-udp
              protocol: UDP
            - containerPort: 8324
              name: plex-roku
              protocol: TCP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 5
              memory: 4Gi
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /config
              name: nfs-plex-config
            - mountPath: /data
              name: nfs-data
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: plex-tcp
  namespace: plexserver
spec:
  selector:
    app: plexserver
  ports:
  - port: 32400
    targetPort: 32400
    name: pms-web
    protocol: TCP
  - port: 8324
    name: plex-roku
    targetPort: 8324
    protocol: TCP
  - port: 32469
    targetPort: 32469
    name: dlna-tcp
    protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: plex-udp
  namespace: plexserver
spec:
  selector:
    app: plexserver
  ports:
  - port: 1900
    targetPort: 1900
    name: dlna-udp
    protocol: UDP
  - port: 5353
    targetPort: 5353
    name: discovery-udp
    protocol: UDP
  - port: 32410
    targetPort: 32410
    name: gdm-32410
    protocol: UDP
  - port: 32412
    targetPort: 32412
    name: gdm-32412
    protocol: UDP
  - port: 32413
    targetPort: 32413
    name: gdm-32413
    protocol: UDP
  - port: 32414
    targetPort: 32414
    name: gdm-32414
    protocol: UDP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex-http-route
  namespace: plexserver
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "plex.snoozyhomelab.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: plex-tcp
      kind: Service
      namespace: plexserver
      port: 32400
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: plex-tcp-route-1
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-tcp-1
  rules:
  - backendRefs:
    - name: plex-tcp
      kind: Service
      namespace: plexserver
      port: 32400
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: plex-udp-route-1
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-udp-1
  rules:
  - backendRefs:
    - name: plex-udp
      kind: Service
      namespace: plexserver
      port: 1900
