apiVersion: v1
kind: Namespace
metadata:
  name: plexserver
  labels:
    shared-gateway-access: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-config
  namespace: plexserver
  labels:
    app: plexserver
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/hdd2T/plex/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-data
  namespace: plexserver
  labels:
    app: plexserver
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/hdd2T/plex/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-pvc-config
  namespace: plexserver
  labels:
    app: plexserver
spec:
  storageClassName: ""
  volumeName: plexserver-pv-nfs-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-pvc-data
  namespace: plexserver
  labels:
    app: plexserver
spec:
  storageClassName: ""
  volumeName: plexserver-pv-nfs-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plexserver
  name: plexserver
  namespace: plexserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plexserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plexserver
    spec:
      volumes:
        - name: nfs-plex-config
          persistentVolumeClaim:
            claimName: plexserver-pvc-config
        - name: nfs-data
          persistentVolumeClaim:
            claimName: plexserver-pvc-data
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: VERSION
              value: docker
            - name: TZ
              value: US/Eastern
          image: linuxserver/plex:latest
          imagePullPolicy: Always
          name: plexserver
          ports:
            - containerPort: 32400
              name: pms-web
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 3005
              name: plex-companion
              protocol: TCP
            - containerPort: 5353
              name: discovery-udp
              protocol: UDP
            - containerPort: 8324
              name: plex-roku
              protocol: TCP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 4Gi
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /config
              name: nfs-plex-config
            - mountPath: /data
              name: nfs-data
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: plex-tcp
  namespace: plexserver
spec:
  selector:
    app: plexserver
  ports:
  - port: 32400
    targetPort: 32400
    name: pms-web
    protocol: TCP
  - port: 8324
    name: plex-roku
    targetPort: 8324
    protocol: TCP
  - port: 32469
    targetPort: 32469
    name: dlna-tcp
    protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: plex-udp
  namespace: plexserver
spec:
  selector:
    app: plexserver
  ports:
  - port: 1900
    targetPort: 1900
    name: dlna-udp
    protocol: UDP
  - port: 5353
    targetPort: 5353
    name: discovery-udp
    protocol: UDP
  - port: 32410
    targetPort: 32410
    name: gdm-32410
    protocol: UDP
  - port: 32412
    targetPort: 32412
    name: gdm-32412
    protocol: UDP
  - port: 32413
    targetPort: 32413
    name: gdm-32413
    protocol: UDP
  - port: 32414
    targetPort: 32414
    name: gdm-32414
    protocol: UDP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex-http-route
  namespace: plexserver
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "plex.snoozyhomelab.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: plex-tcp
      kind: Service
      namespace: plexserver
      port: 32400
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: plex-tcp-route-1
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-tcp-1
  rules:
  - backendRefs:
    - name: plex-tcp
      kind: Service
      namespace: plexserver
      port: 32400
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: plex-tcp-route-2
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-tcp-2
  rules:
  - backendRefs:
    - name: plex-tcp
      kind: Service
      namespace: plexserver
      port: 8324
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: plex-tcp-route-3
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-tcp-3
  rules:
  - backendRefs:
    - name: plex-tcp
      kind: Service
      namespace: plexserver
      port: 32469
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: plex-udp-route-1
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-udp-1
  rules:
  - backendRefs:
    - name: plex-udp
      kind: Service
      namespace: plexserver
      port: 1900
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: plex-udp-route-2
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-udp-2
  rules:
  - backendRefs:
    - name: plex-udp
      kind: Service
      namespace: plexserver
      port: 5353
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: plex-udp-route-3
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-udp-3
  rules:
  - backendRefs:
    - name: plex-udp
      kind: Service
      namespace: plexserver
      port: 32410
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: plex-udp-route-4
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-udp-4
  rules:
  - backendRefs:
    - name: plex-udp
      kind: Service
      namespace: plexserver
      port: 32412
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: plex-udp-route-5
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-udp-5
  rules:
  - backendRefs:
    - name: plex-udp
      kind: Service
      namespace: plexserver
      port: 32413
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: plex-udp-route-6
  namespace: plexserver
spec:
  parentRefs:
  - name: main-gateway
    namespace: envoy-gateway-system
    sectionName: plex-udp-6
  rules:
  - backendRefs:
    - name: plex-udp
      kind: Service
      namespace: plexserver
      port: 32414
