apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: homelab
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./plex/config
        containerPath: /mnt/ssd/plex/config
      - hostPath: ./plex/data
        containerPath: /mnt/ssd/plex/data
      - hostPath: ./plex/data/movies
        containerPath: /mnt/ssd/plex/data/movies
      - hostPath: ./plex/data/photos
        containerPath: /mnt/ssd/plex/data/photos
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP