apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-pvc-config
  namespace: plexserver
  labels:
    app: plexserver
spec:
  storageClassName: zimablade-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexserver-pvc-data
  namespace: plexserver
  labels:
    app: plexserver
spec:
  storageClassName: zimablade-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti